ElectronicColorCode/Models/ECC.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ElectronicColorCode.Models
{
    public class ECC : IOhmValueCalculator
    {
        [Required(ErrorMessage = "Please select a value for Band 1")]
        [Display(Name = "Band1")]
        public string BandAColor { get; set; }
        public IEnumerable<SelectListItem> BandAColors { get; set; }

        [Required(ErrorMessage = "Please select a value for Band 2")]
        [Display(Name = "Band2")]
        public string BandBColor { get; set; }
        public IEnumerable<SelectListItem> BandBColors { get; set; }

        [Required(ErrorMessage = "Please select a value for Band 3")]
        [Display(Name = "Multiplier")]
        public string BandCColor { get; set; }
        public IEnumerable<SelectListItem> BandCColors { get; set; }

        [Required(ErrorMessage = "Please select a value for Band ")]
        [Display(Name = "Tolerance")]
        public string BandDColor { get; set; }
        public IEnumerable<SelectListItem> BandDColors { get; set; }

        [Display(Name = "Ohm Value")]
        public double OhmValue { get; set; }

        [Display(Name = "Upper Bound")]
        public double UpperBoundValue { get; set; }

        [Display(Name = "Lower Bound")]
        public double LowerBoundValue { get; set; }

        public ECC()
        {
            this.OhmValue = 0;
            BandDColor = "None";
        }

        public static readonly Dictionary<String, double> Tolerance = new Dictionary<string, double>
        {
            {"None",20 },
            {"Silver", 10},
            {"Gold", 5 },
            {"Brown", 1 },
            {"Red", 2 },
            {"Green",0.5 },
            {"Blue",0.25 },
            {"Violet",0.1 },
            {"Gray",0.05 }
        };

        //TODO Add functionality for error range
        public double CalculateOhmValue(string bandAColor, string bandBColor, string bandCColor)
        {
            if (bandAColor != null &&
                bandBColor != null &&
                bandCColor != null)
            {
                if (Enum.IsDefined(typeof(IecSignificantFigures), bandAColor) &&
                        Enum.IsDefined(typeof(IecSignificantFigures), bandBColor))
                {
                    int significantFigure = (int)Enum.Parse(typeof(IecSignificantFigures), bandAColor) * 10 + (int)Enum.Parse(typeof(IecSignificantFigures), bandBColor);

                    if (Enum.IsDefined(typeof(IecSignificantFigures), bandCColor))
                    {
                        return significantFigure * Math.Pow(10, (int)Enum.Parse(typeof(IecSignificantFigures), bandCColor));
                    }
                    else if (Enum.IsDefined(typeof(IecFractionalMultiplier), bandCColor))
                    {
                        double temp = significantFigure * Math.Pow(10, (int)Enum.Parse(typeof(IecFractionalMultiplier), bandCColor) * -1);
                        return Math.Round(temp, (int)Enum.Parse(typeof(IecFractionalMultiplier), bandCColor));
                    }
                }
            }
            return -1;
        }

        public void Calculate()
        {
            this.OhmValue = CalculateOhmValue(BandAColor, BandBColor, BandCColor);
            this.UpperBoundValue = CalculateUpperBoundValue(BandDColor);
            this.LowerBoundValue = CalculateLowerBoundValue(BandDColor);
        }

        public double CalculateUpperBoundValue(string bandDColor)
        {
            if (CalculateTolerance(out double toleranceValue, bandDColor))
            {
                return OhmValue + toleranceValue;
            }
            return -1;
        }

        public double CalculateLowerBoundValue(string bandDColor)
        {

            if (CalculateTolerance(out double toleranceValue, bandDColor))
            {
                return OhmValue - toleranceValue;
            }
            return -1;
        }

        private bool CalculateTolerance(out double toleranceValue, string bandDColor)
        {
            toleranceValue = -1;
            if (bandDColor != null &&
                  OhmValue != -1 &&
                  Tolerance.TryGetValue(bandDColor, out double tolerance))
            {
                toleranceValue = OhmValue * tolerance / 100;
                return true;
            }
            return false;
        }
    }
}

ElectronicColorCode/Models/IOhmValueCalculator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ElectronicColorCode.Models
{
    //TODO Decide how to include pink silver gold and none
    public enum IecSignificantFigures
    {
        Black,
        Brown,
        Red,
        Orange,
        Yellow,
        Green,
        Blue,
        Violet,
        Gray,
        White
    }

    public enum IecFractionalMultiplier
    {
        Gold = 1,
        Silver,
        Pink
    }

    public interface IOhmValueCalculator
    {
        /// <summary>

        /// Calculates the Ohm value of a resistor based on the band colors.

        /// </summary>

        /// <param name="bandAColor">The color of the first figure of component value band.</param>

        /// <param name="bandBColor">The color of the second significant figure band.</param>

        /// <param name="bandCColor">The color of the decimal multiplier band.</param>

        /// <param name="bandDColor">The color of the tolerance value band.</param>
        double CalculateOhmValue(string bandAColor, string bandBColor, string bandCColor);
        double CalculateUpperBoundValue(string bandDColor);
        double CalculateLowerBoundValue(string bandDColor);
    }
}

ElectronicColorCode/Controllers/ECCController.cs
using ElectronicColorCode.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ElectronicColorCode.Controllers
{
    public class ECCController : Controller
    {
        private static ECC ecc = new ECC();

        // GET: ECC
        public ActionResult Index()
        {
            var colorAList = GetAllColors();
            var colorBList = GetAllColors();
            var multiplierList = GetMultipliersColors();
            var toleranceList = GetToleranceColors();

            // Create a list of SelectListItems so these can be rendered on the page
            ecc.BandAColors = GetSelectListItems(colorAList);
            ecc.BandBColors = GetSelectListItems(colorBList);
            ecc.BandCColors = GetSelectListItems(multiplierList);
            ecc.BandDColors = GetSelectListItems(toleranceList);

            return View(ecc);
        }

        [HttpPost]
        public ActionResult Index(ECC model)
        {
            var colorAList = GetAllColors();
            var colorBList = GetAllColors();
            var multiplierList = GetMultipliersColors();
            var toleranceList = GetToleranceColors();

            model.BandAColors = GetSelectListItems(colorAList);
            model.BandBColors = GetSelectListItems(colorBList);
            model.BandCColors = GetSelectListItems(multiplierList);
            model.BandDColors = GetSelectListItems(toleranceList);


            if (ModelState.IsValid)
            {
                Session["ECCModel"] = model;
                Calculate();
            }

            return View("Index", model);

        }

        public void Calculate()
        {
            var model = Session["ECCModel"] as ECC;
            model.Calculate();
        }

        private IEnumerable<SelectListItem> GetSelectListItems(IEnumerable<string> colorList)
        {
            var selectList = new List<SelectListItem>();

            foreach (var element in colorList)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element,
                    Text = element
                });
            }

            return selectList;
        }

        private IEnumerable<string> GetToleranceColors()
        {
            return ECC.Tolerance.Keys;
        }

        private IEnumerable<string> GetMultipliersColors()
        {
            List<string> positiveMultipliersList = Enum.GetNames(typeof(IecSignificantFigures)).ToList();
            List<string> fractionalMultipliersList = Enum.GetNames(typeof(IecFractionalMultiplier)).ToList();
            return fractionalMultipliersList.Concat(positiveMultipliersList);
        }

        private IEnumerable<string> GetAllColors()
        {
            return Enum.GetNames(typeof(IecSignificantFigures)).ToList();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View("Contact");
        }
    }
}

ElectronicColorCode/Views/ECC/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<address>
   Ann Stephen<br />
    <a href="mailto:ann.stephen.88@gmail.com">ann.stephen.88@gmail.com</a><br />
    <a href="https://github.com/annstephen/ElectronicColorCode" target="_blank">Github Repository</a><br />
</address>

ElectronicColorCode/Views/ECC/Index.cshtml
@using ElectronicColorCode.Models
@model ECC
@{
    ViewBag.Title = "Resistor Calculator";
}

<h2>Resistor Calculator</h2>

<div class="form-group" id="index">
    @using (Html.BeginForm("Index", "ECC", FormMethod.Post, new { role = "form" }))
    {
    <div class="row">
        <div class="col-lg-5">            
            <div class="row">
                @Html.LabelFor(m => m.BandAColor)
                @Html.DropDownListFor(m => m.BandAColor, Model.BandAColors, "Select a color for band A", new {id="bandA", @class = "form-control", onchange= "updateStyle(bandA)" })
                @Html.ValidationMessageFor(m => m.BandAColor)
            </div>
            <br />
            <div class="row">
                @Html.LabelFor(m => m.BandBColor)
                @Html.DropDownListFor(m => m.BandBColor, Model.BandBColors, "Select a color for band B", new { id = "bandB", @class = "form-control", onchange= "updateStyle(bandB)" })
                @Html.ValidationMessageFor(m => m.BandBColor)
            </div>
            <br />
            <div class="row">
                @Html.LabelFor(m => m.BandCColor)
                @Html.DropDownListFor(m => m.BandCColor, Model.BandCColors, "Select a color for band C", new { id = "bandC", @class = "form-control", onchange = "updateStyle(bandC)" })
                @Html.ValidationMessageFor(m => m.BandCColor)
            </div>
            <br />
            <div class="row">
                @Html.LabelFor(m => m.BandDColor)
                @Html.DropDownListFor(m => m.BandDColor, Model.BandDColors, new { id = "bandD", @class = "form-control", @Value="None", onchange = "updateStyle(bandD)" })
                @Html.ValidationMessageFor(m => m.BandDColor)
            </div>
            <br />
        </div>
        <div class="col-lg-5 text-center">
            <br />
            <div class="row">
                @Html.LabelFor(m => m.OhmValue)
                @Html.DisplayTextFor(m => m.OhmValue)
            </div>
            <br />
            <div class="row">
                @Html.LabelFor(m => m.UpperBoundValue)
                @Html.DisplayTextFor(m => m.UpperBoundValue)
            </div>
            <br />
            <div class="row">
                @Html.LabelFor(m => m.LowerBoundValue)
                @Html.DisplayTextFor(m => m.LowerBoundValue)
            </div>
            <br />
        </div>
    </div>
    <div class="row">
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Calculate</button>
        </div>
    </div>
    }
</div>

ElectronicColorCode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  Electronic Color Code</title>
    <script type="text/javascript">
        function loadColors(page) {
            if (page.document.title == "Resistor Calculator Electronic Color Code") {
                updateStyleById("bandA");
                updateStyleById("bandB");
                updateStyleById("bandC");
                updateStyleById("bandD");
            }
        };
        function updateStyle(select) {
            updateStyleById(select.id);
        }
        function updateStyleById(id) {
            var select = document.getElementById(id);
            var value = select.options[select.selectedIndex];
            if (value.text != "None") {
                var style = window.getComputedStyle ? getComputedStyle(value, null) : value.currentStyle;
                select.style.color = style.getPropertyValue("color");
                select.style.backgroundColor = value.text;
            }
            else {
                select.style.backgroundColor = "White";
                select.style.color = "Black";
            }
        }
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body  onload="loadColors(this
    )">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Electronic Color Code", "Index", "ECC", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact", "Contact", "ECC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        <div class="container">
            @RenderBody()
        </div>
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - Ann's ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>